<?php

/**
 * @file
 * Contains jon_custom_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jon_custom_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jon_custom_rest module.
    case 'help.page.jon_custom_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('jon_custom_module_description') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jon_custom_rest_theme() {
  return [
    'jon_custom_rest' => [
      'render element' => 'children',
    ],
  ];
}
