<?php

/**
 * @file
 * Contains d8_guzzlenode_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_guzzlenode_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_guzzlenode_rest module.
    case 'help.page.d8_guzzlenode_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('D8 add REST exports to guzzlerestgenerator module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_guzzlenode_rest_theme() {
  return [
    'd8_guzzlenode_rest' => [
      'render element' => 'children',
    ],
  ];
}
