<?php

/**
 * @file
 * Contains d8_guzzlenode_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_rest_entity_form_alter(). ENABLE the 2 new guzzlenode fields 
 */
function d8_guzzlenode_rest_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //ENABLE all our custom fileds.(we do that because this module add the fields to an already existing form -so /config/install/optional will NOT work)
    $fields_to_enable=array('field_guzzlenode_user_api_access',
                            'field_guzzlenode_role_api_access',
                            'field_guzzlenode_call_limit',
                            'field_gnode_allow_arg_fwd',
                            'field_gnode_allow_head_fwd',
                            'field_gnode_allow_param_fwd',
                            'field_gnode_allow_payload_fwd'
    );

    foreach ($fields_to_enable as $field) {
        \Drupal::entityTypeManager()
          ->getStorage('entity_form_display')
          ->load('node.guzzle_rest.default')  //orig ->load('user.user.default')
          ->setComponent($field
            /*, [
              //'type' => 'string',
              'label' => 'above',
              //'settings' => ['link_to_entity' => 'false'],
          ]
          */
        )->save(); 
    }//END of foreach ($fields_to_enable as $field) {

//      \Drupal::logger('DEBUG d8_guzzlenode_rest')->notice("jon CUSTOM entity_form_display   "); //DEBUG   

} // END of function d8_guzzlenode_rest_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {


/**
 * Implements hook_rest_entity_base_field_info(). CUSTOM field
 */
/*
function d8_guzzlenode_rest_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type
    ->id() == 'guzzle_rest') {
    $fields = [];


    $fields['guzzle_api_user_access'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Users allowed'))
      ->setDescription(t('users that are allowed to access this External API'))
      ->setRevisionable(FALSE)
      ->setSetting('target_type', 'user')
      ->setSetting('handler', 'default')
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setTranslatable(FALSE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'author',
        'weight' => 0,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 5,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    \Drupal::logger('DEBUG d8_guzzlenode_rest')->notice("jon CUSTOM FIELD CREATED   "); //DEBUG
    return $fields;
  }
}
*/

/**
 * Implements hook_help(). (auto-generated)
 */
function d8_guzzlenode_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_guzzlenode_rest module.
    case 'help.page.d8_guzzlenode_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('D8 add REST exports to guzzlerestgenerator module') . '</p>';
      return $output;

    default:
  }
}



/**
 * Implements hook_theme(). (auto-generated)
 */
function d8_guzzlenode_rest_theme() {
  return [
    'd8_guzzlenode_rest' => [
      'render element' => 'children',
    ],
  ];
}
